### ISSUE TITLE
Compilation failure (language.c)

### ISSUE THREAD

**Issue by ParzivalWolfram** [jwt27/watt32#1]
As I can't capture stderr in MS-DOS 6.22, i've attached a video of compilation, which may be used to read all errors. Not ideal, I know, but I can't do much about it...
[recording.zip](https://github.com/jwt27/watt32/files/3990669/recording.zip)

**Comment by jwt27** [comment]
This repository only exist for cross-compiling from linux/windows to djgpp. If you want to compile on DOS you should download the official version from http://www.watt-32.net/ and follow the instructions in the `install` file.
The latest v2.2-11 release already supports cross-compiling out of the box, even though it's not particularly well documented, so I should probably delete this repository.

**Comment by ParzivalWolfram** [comment]
Noted.
